export enum TileType {
  NONE = 'None',
  ANY = 'Any',
  BEACH = 'Beach',
  BROKEN_LANDS = 'Broken Lands',
  DEAD_FOREST = 'Dead Forest',
  DESERT = 'Desert',
  DESERT_CACTUS = 'Cactus Desert',
  FARMLAND = 'Farmland',
  FOREST = 'Forest',
  FUNGAL_FOREST = 'Fungal Forest',
  GRASSLANDS = 'Grasslands',
  HILLS = 'Hills',
  JUNGLE = 'Jungle',
  MOUNTAIN = 'Mountain',
  NEEDLE_FOREST = 'Needle Forest',
  OCEAN = 'Ocean',
  SAVANNAH = 'Savannah',
  SEA = 'Sea',
  SHOAL = 'Shoals',
  SNOW = 'Snow',
  SWAMP = 'Swamp',
}
